DROP TABLE IF EXISTS location;

CREATE TABLE location (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    lat TEXT NOT NULL,
    lng TEXT NOT NULL,
    zoom TEXT NOT NULL
);

DROP TABLE IF EXISTS history;

CREATE TABLE history(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    loc_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mapimage TEXT NOT NULL,
    greyimage TEXT NOT NULL,
    greencover FLOAT NOT NULL,
    greenarea FLOAT NOT NULL,
    totalarea FLOAT NOT NULL
);

